apache-drupal:
  image: espressodev/apache-fpm-drupal
  container_name: apache-drupal
  ports:
   - "8008:80"
  volumes:
   - /var/www
   - /var/files
  environment:
    VIRTUAL_HOST: drupal.loc
    DRUPAL_USER: admin
    DRUPAL_PASSWORD: admin
    MYSQL_USER: root
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: drupal
    MYSQL_HOST: mysql
    SITE_INSTAL: true
    PHP_MEMORY_LIMIT: 512M
    PHP_POST_MAX_SIZE: 512M
  hostname: drupal.loc
  links:
   - mysql
mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: drupal
    MYSQL_DATABASE: drupal
  ports:
    - "3306"